name: publish to github package registry

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matootie/github-docker@v2.2.3
        with:
          accessToken: ${{ secrets.GIT_TOKEN }}